# Generated by Django 5.0.7 on 2024-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_first_name_alter_myuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обычный пользователь'), (2, 'Менеджер'), (3, 'Бухгалтер')], default=1, verbose_name='Статус пользователя'),
        ),
    ]
