# Generated by Django 5.0.7 on 2024-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описнаие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('location_event', models.CharField(max_length=150, verbose_name='Место проводение')),
                ('image', models.ImageField(upload_to='media/images/', verbose_name='Изображение')),
                ('event_date', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('date_duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во билетов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание объекта')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
