# Generated by Django 5.0.7 on 2024-07-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во билетов')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заказ обработке'), (2, 'Заказ оплачен'), (3, 'Заказ отменен')], default=1, verbose_name='Статус')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание объекта')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.ticket', verbose_name='Билет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
